### ISSUE TITLE
tcconfig kali 

### ISSUE THREAD

**Issue by sanhar** [thombashi/tcconfig#106]
I am newbie to network and firewall system.  

I installed kali linux latest version. 
it contains python3.7.2+ 

tcconfig was installed with pip3 

When I run '  tcset ens3 --delay 10sec --rate 1bps --network <remote_ip_address> --direction incoming ' on console, I got errors as following. 

[ERROR] tcconfig: command execution failed
  command=/usr/sbin/tc class add dev ifb5634 parent 1602: classid 1602:2 htb rate 0.001Kbit ceil 0.001Kbit burst 1.25e-05KB cburst 1.25e-05KB
  stderr="rate" is required.

[ERROR] tcconfig: command execution failed
  command=/usr/sbin/tc qdisc add dev ifb5634 parent 1602:2 handle 2bb2: netem delay 10sec
  stderr=Error: Specified class not found.

Could someone explain why the errors mean and how to fix it ?

**Comment by thombashi** [comment]
@sanhar 
Thank you for your report.

Could you try to set `8bps` or greater value to `--rate` option?
The minimum valid rate of `tc` is `8bps` according to the `tc` source code:

https://github.com/shemminger/iproute2/blob/707f612c00a91fe3c17d7af5319e423545a496c5/tc/q_htb.c#L202-L205
https://github.com/shemminger/iproute2/blob/707f612c00a91fe3c17d7af5319e423545a496c5/tc/tc_util.c#L155-L158

**Comment by thombashi** [comment]
I had fixed the minimum bandwidth rate validation at `tcconfig 0.21.8`.

**Comment by thombashi** [comment]
I'll close the issue.
Feel free to reopen if you still have any problems about the issue.
