### ISSUE TITLE
Internal Error while deleting rules

### ISSUE THREAD

**Issue by dufferzafar** [thombashi/tcconfig#107]
Sometimes I get this error when running `sudo tcdel ens3 --all`:

When I run the command again, it works.

```
[2187] INTERNAL ERROR: cannot create temporary directory!
```

**Comment by thombashi** [comment]
@dufferzafar 
Thank you for your report.

Is there free disk space for your root file system?
The error may occur when no disk space available.

**Comment by dufferzafar** [comment]
@thombashi Yes, that is what the issue was. Thanks.
