### ISSUE TITLE
confuse with docker rate limit

### ISSUE THREAD

**Issue by S3cuRiTy-Er1C** [thombashi/tcconfig#113]
Hi sir,
I recently use tcconfig to set up some tc rules, but when I use --docker options(like this: `tcset vpn_service --docker --rate 1mbps`) the vpn_service docker might can't connect the internet. please help.
thanks a lot!

**Comment by thombashi** [comment]
Hi,

Thank you for your report.

Unfortunately, I could not reproduce the issue. A container still can connect the internet after tcset in my environment (Ubuntu 18.04, tcconfig 0.22.2, Docker 18.09.5).
Could you provide some more information? The following information would be helpful:

- tcconfig version
- OS distro/version
- Docker version
- Your operatios to reproduce the issue
- Error logs if there are any

**Comment by S3cuRiTy-Er1C** [comment]
Hi,
The following details are my environment information.
* tcset version is 0.22.1
* ubuntu 16.04 x64 `4.4.0-143-generic`
* docker version(client and server both are `18.06.1-ce stable`)
* strongswan service running in the docker, basic image is alpine latest, mirror port is using default 500 and 4500, network settings are used docker default bridge mode.
