### ISSUE TITLE
Question: How to use from python?

### ISSUE THREAD

**Issue by MatthiasLohr** [thombashi/tcconfig#114]
Hey

nice tool! Is there any documentation about using `tcset` directly from python code?

Best regards
Matthias

**Comment by thombashi** [comment]
Hi,

Unfortunately, there is no documentation for usage as a library for now.
I would add in the future.

You could use `tcset` as library via `TrafficControl` class:
https://github.com/thombashi/tcconfig/blob/a0bdfaf3ce9cff5450740b0631b75fa1102bf618/tcconfig/traffic_control.py#L37

`TcSetMain` class could be an example for this:
https://github.com/thombashi/tcconfig/blob/a0bdfaf3ce9cff5450740b0631b75fa1102bf618/tcconfig/tcset.py#L225-L323

For a while, I would answer your questions if you have any.

**Comment by V4Vendetta97** [comment]
hey!  is there any documentation now about using tcset directly from python code?
thank you for this tool !

**Comment by V4Vendetta97** [comment]
TcSetMain(Main)
where can i find the class Main?
