### ISSUE TITLE
Plan to add a parameter for netem limit attribute

### ISSUE THREAD

**Issue by stephenyin** [thombashi/tcconfig#118]
Hi
Any plan to add a parameter for netem limit attribute. It is very important for queuing in bandwidth limitation.

`/sbin/tc qdisc add dev ifb6711 parent 1a37:2 handle 1ab7: netem limit 200`

http://manpages.ubuntu.com/manpages/disco/en/man8/tc-netem.8.html

> limit packets
>        maximum number of packets the qdisc may hold queued at a time.

Thanks.

**Comment by stephenyin** [comment]
Fixed on my fork：https://github.com/stephenyin/tcconfig

**Comment by nmcconom** [comment]
Any plans to merge this change with the master so that pip install tcconfig would pick it up?
