### ISSUE TITLE
Rate limiting on outgoing traffic for an interface 

### ISSUE THREAD

**Issue by kaldughayem** [thombashi/tcconfig#119]
I have set the rate for outgoing traffic for an interface (a docker network interface) on my host machine with the command 
```sudo tcset --add --rate 1Mbps --direction outgoing br-efc11fc24f8f```
`br-efc11fc24f8f` is the docker interface. Then went to measure the bandwidth using iperf3 from a docker container connected to the network of that interface and got the following outputs:

iperf3 client output (in docker container):

    Connecting to host 172.18.0.1, port 12345
    [  4] local 172.18.0.4 port 54828 connected to 172.18.0.1 port 12345
    [ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
    [  4]   0.00-1.00   sec   201 MBytes  1.69 Gbits/sec    0   3.12 MBytes       
    [  4]   1.00-2.00   sec   115 MBytes   965 Mbits/sec    0   3.12 MBytes       
    [  4]   2.00-3.00   sec   112 MBytes   944 Mbits/sec    0   3.12 MBytes       
    [  4]   3.00-4.00   sec  97.5 MBytes   818 Mbits/sec    0   3.12 MBytes       
    [  4]   4.00-5.00   sec   109 MBytes   912 Mbits/sec    0   3.12 MBytes       
    [  4]   5.00-6.00   sec   114 MBytes   954 Mbits/sec    0   3.12 MBytes       
    [  4]   6.00-7.00   sec   120 MBytes  1.01 Gbits/sec    0   3.12 MBytes       
    [  4]   7.00-8.00   sec   111 MBytes   933 Mbits/sec    0   3.12 MBytes       
    [  4]   8.00-9.00   sec   109 MBytes   912 Mbits/sec    0   3.12 MBytes       
    [  4]   9.00-10.00  sec   116 MBytes   975 Mbits/sec    0   3.12 MBytes       
    - - - - - - - - - - - - - - - - - - - - - - - - -
    [ ID] Interval           Transfer     Bandwidth       Retr
    [  4]   0.00-10.00  sec  1.18 GBytes  1.01 Gbits/sec    0             sender
    [  4]   0.00-10.00  sec  1.18 GBytes  1.01 Gbits/sec                  receiver
    
    iperf Done.

iperf3 server (on host machine listening on the interface's IP address 172.18.0.1):

    Accepted connection from 172.18.0.4, port 54826
    [  5] local 172.18.0.1 port 12345 connected to 172.18.0.4 port 54828
    [ ID] Interval           Transfer     Bandwidth
    [  5]   0.00-1.00   sec   198 MBytes  1.66 Gbits/sec                  
    [  5]   1.00-2.00   sec   115 MBytes   968 Mbits/sec                  
    [  5]   2.00-3.00   sec   112 MBytes   941 Mbits/sec                  
    [  5]   3.00-4.00   sec  97.5 MBytes   818 Mbits/sec                  
    [  5]   4.00-5.00   sec   108 MBytes   908 Mbits/sec                  
    [  5]   5.00-6.00   sec   114 MBytes   959 Mbits/sec                  
    [  5]   6.00-7.00   sec   119 MBytes  1.00 Gbits/sec                  
    [  5]   7.00-8.00   sec   110 MBytes   927 Mbits/sec                  
    [  5]   8.00-9.00   sec   110 MBytes   920 Mbits/sec                  
    [  5]   9.00-10.00  sec   115 MBytes   968 Mbits/sec                  
    [  5]  10.00-10.04  sec  4.20 MBytes   887 Mbits/sec                  
    - - - - - - - - - - - - - - - - - - - - - - - - -
    [ ID] Interval           Transfer     Bandwidth       Retr
    [  5]   0.00-10.04  sec  1.18 GBytes  1.01 Gbits/sec    0             sender
    [  5]   0.00-10.04  sec  1.18 GBytes  1.01 Gbits/sec                  receiver

When I do the same thing but for incoming traffic, I get no problems and iperf reports a bandwidth close to 1 Mbps:
iperf3 client (docker container):
    
    [ ID] Interval           Transfer     Bandwidth       Retr
    [  4]   0.00-10.00  sec  3.70 MBytes  3.11 Mbits/sec    1             sender
    [  4]   0.00-10.00  sec  1.75 MBytes  1.47 Mbits/sec                  receiver

    iperf Done.

iperf server (on host machine): 

    [ ID] Interval           Transfer     Bandwidth       Retr
    [  5]   0.00-14.43  sec  3.70 MBytes  2.15 Mbits/sec    1             sender
    [  5]   0.00-14.43  sec  1.75 MBytes  1.02 Mbits/sec                  receiver

I do not know if I missed a parameter, or if it is something with how iperf works but I am trying to set the bandwidth on the outgoing traffic at 1Mbps.    

I'm running it on an Ubuntu 16.04.
Docker version 18.09.7

Thanks.

**Comment by thombashi** [comment]
@kaldughayem 

Thank you for your report.
Did you already try with `--docker` option? like 
`sudo tcset --add --rate 1Mbps --direction outgoing <container id> --docker`.
