### ISSUE TITLE
Rules do not apply to custom docker container interface 

### ISSUE THREAD

**Issue by rukmarr** [thombashi/tcconfig#120]
Hi

I really enjoy using tcconfig, but there is one problem I ran into:
I'm using ip and tinc VPN to setup virtual interface on the host and then move it into docker container like this:

```shell
pid=$(/usr/local/bin/docker inspect -f "{{{{.State.Pid}}}}" "{c_id}");
if [ ! -e /var/run/netns/$pid ]; then  
    echo "No netns, making one rn"  
    ln -s /proc/$pid/ns/net /var/run/netns/$pid  
fi  
ip link set tun{idx} netns $pid;  
ip -n $pid address add dev tun{idx} {ip};  
ip -n $pid link set tun{idx} up
```

However, when I'm trying to set rules for the container via tcconfig, nothing changes.
For instance, even with a 100% loss, container still can communicate through the virtual interface.

If I'm not mistaken, tcconfig uses docker to gather information about container networking. And of course, docker will know nothing about a virtual interface added like this. I managed to partially mimic the desired functionality using `ip netns exec $pid tcset --loss 100% tun{idx}`, but I don't see any way to set rules for all container interfaces at once, like with --docker.

Does tcconfig have an option to apply rules to all interfaces in the current network namespace?  If no, is there any other way to mimic --docker functionality for custom interfaces? 

Thanks

**Comment by thombashi** [comment]
@rukmarr 
Hi,
Thank you for your feedback.

>Does tcconfig have an option to apply rules to all interfaces in the current network namespace?

Unfortunately, `tcset` command has no such option.
when using `--docker` option:

```
pid=$(/usr/local/bin/docker inspect -f "{{{{.State.Pid}}}}" "{c_id}");
if [ ! -e /var/run/netns/$pid ]; then  
    echo "No netns, making one rn"  
    ln -s /proc/$pid/ns/net /var/run/netns/$pid  
fi  
```

up to this point, `tcset` behaves almost the same.
then, execute the following and find `veth` pairs (one at the container and the other at the docker host) from the command output:

```sh
ip netns exec <container> ip link show type veth
ip link show type veth
```

And then, set a shaping rule to the found device.
I'm not sure this can be applied to a tun device though.
