### ISSUE TITLE
Limit rate to 32Gbps when adding delay

### ISSUE THREAD

**Issue by MataNIr89** [thombashi/tcconfig#122]
OS: RH7.5
kernel:3.10.0-957.el7.x86_64

> $ tcshow ens1f0
> {
>     "ens1f0": {
>         "outgoing": {},
>         "incoming": {}
>     }
> }
> 

after entering the command :

> tcset ens1f0 --delay 10ms --direction incoming

i get:

> $ tcshow ens1f0
> {
>     "ens1f0": {
>         "outgoing": {},
>         "incoming": {
>             "protocol=ip": {
>                 "delay": "10.0ms",
>                 "rate": "32Gbps",
>                 "filter_id": "800::800"
>             }
>         }
>     }
> }

**Comment by thombashi** [comment]
This is an expected behavior.
`tcset` will be adding the root rule that an unlimited rate even if a rate option is not specified, in favor to add child rules.
However, `tc` can not set an unlimited rate though, `tcset` calculate and set the possible maximum rate instead.
