### ISSUE TITLE
Cannot load settings for docker container

### ISSUE THREAD

**Issue by Lawouach** [thombashi/tcconfig#127]
Let's say you set a rule on a container. When you try to set the same rule via the setting file, it cannot find the device because the generated `tcset` command in _importer.py doesn't support adding the `--docker` argument that would be required.

**Comment by thombashi** [comment]
@Lawouach 
Thank you for your report.

I had fixed the problem at `tcconfig 0.24.0`. Now you can import config like below:

```json
{
    "edfd9dbb3969 (device=veth6f7b798)": {
        "outgoing": {
            "protocol=ip": {
                "rate": "1Mbps",
            }
        },
        "incoming": {}
    }
}
```

**Comment by Lawouach** [comment]
Ohhhh that is neat, I didn't know that :)

**Comment by thombashi** [comment]
I'll close the issue.
Feel free to reopen if you still have any problems about the issue.
