### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by thombashi** [thombashi/tcconfig#128]
`tcconfig 0.24.x` series will be the last version that supports Python 2.
edit: Python 2 support is dropped at `tcconfig 0.25.0`

tcconfig `1.0.0` or newer includes several breaking changes:

- `tcset`/`tcshow`/`tcdel` will become a single command (`tcconfig`)
  - to reduce file size of the binary package
  - to be more easily add sub-commands
  - `tcxxx` commands will be sub-commands of `tcconfig` command
    - command aliases may keep left for backward compatibility
- Change import/export functionality/file-format
- tcconfig server/client

**Comment by Lawouach** [comment]
The tconfig server/client is gold for me! This is exactly what I'm building to wrap tcconfig into a REST API. But I'd rather benefit from yours instead!

**Comment by leond08** [comment]
waiting for this :)

**Comment by thombashi** [comment]
I will continue to update this project.
However, the time available for this project is still limited.
So, the updates and solving issues will take a long time. Or I should think about looking for new maintainers.
