### ISSUE TITLE
'Exclusivity flag on, cannot modify.' error when adding multiple --dst-network rules

### ISSUE THREAD

**Issue by ClydeAmazing** [thombashi/tcconfig#131]
Hello,
Great work on this very helpful tool!
I am trying to implement multiple rules using the following commands:

`tcset eth1 --dst-network 10.0.0.3 --rate 1mbps --direction incoming`
`tcset eth1 --dst-network 10.0.0.90 --rate 1mbps --direction incoming`

While the first command seems to execute correctly, the second (succeeding) command(s) returns the following error: 
`tcconfig: command execution failed
stderr=Error: Exclusivity flag on, cannot modify.`

Did I miss something here?

**Comment by thombashi** [comment]
Hello,
Thank you for your report.

How about the second command executing with `--add` option.
If still failed, please provide me the following information:

- a full execution error log with `--debug` option.
- environmental information: `uname -a` output, tcconfig version, Python version, etc.

**Comment by ultamatt** [comment]
I am also seeing this error. 

`open@redskull:~$ sudo tcdel mgmt0 --all
[WARNING] command='/usr/sbin/tc qdisc del dev mgmt0 root', returncode=2, stderr='Error: Cannot delete qdisc with handle of zero.\n'
[WARNING] no qdisc to delete for the incoming device.
open@redskull:~$ sudo tcset mgmt0 --rate 2Mbps --network 192.168.7.99
open@redskull:~$ sudo tcshow mgmt0
{
    "mgmt0": {
        "outgoing": {
            "dst-network=192.168.7.99/32, protocol=ip": {
                "filter_id": "800::800",
                "rate": "2Mbps"
            }
        },
        "incoming": {}
    }
}
open@redskull:~$ sudo tcset mgmt0 --rate 4Mbps --network 192.168.7.98 --add --debug
DEBUG    | subprocrunner._subprocess_runner:__debug_print_command:264 - lsmod
DEBUG    | simplesqlite.core:connect:265 - connect to a SQLite database: path=':memory:', mode=w
DEBUG    | simplesqlite.core:create_table:1261 - CREATE TABLE IF NOT EXISTS 'filter' (device TEXT NOT NULL, "filter_id" TEXT, flowid TEXT, protocol TEXT, priority INTEGER, [src-network] TEXT, [dst-network] TEXT, [src-port] INTEGER, [dst-port] INTEGER, classid TEXT, handle INTEGER)
DEBUG    | simplesqlite.core:create_table:1261 - CREATE TABLE IF NOT EXISTS 'qdisc' (device TEXT NOT NULL, "direct_qlen" INTEGER, parent TEXT NOT NULL, handle TEXT NOT NULL, delay TEXT, [delay-distro] TEXT, loss TEXT, duplicate TEXT, corrupt TEXT, reorder TEXT, rate TEXT)
DEBUG    | subprocrunner._subprocess_runner:__debug_print_command:264 - /usr/sbin/tc filter show dev mgmt0 root
DEBUG    | subprocrunner._subprocess_runner:__debug_print_command:264 - /usr/sbin/tc class show dev mgmt0
DEBUG    | tcconfig.parser._class:parse:47 - parse a class entry: {'device': 'mgmt0', 'classid': '1f36:1', 'rate': '10Gbps'}
DEBUG    | tcconfig.parser._class:parse:47 - parse a class entry: {'device': 'mgmt0', 'classid': '1f36:2', 'rate': '2Mbps'}
DEBUG    | simplesqlite.core:__create_table_from_tabledata:1702 - __create_table_from_tabledata:
    tbldata=table_name=class, headers=[device, classid, rate], cols=3, rows=2
DEBUG    | tabledata.normalizer:normalize:58 - normalize: SQLiteTableDataSanitizer
DEBUG    | dataproperty._extractor:to_dp_matrix:442 - max_workers = 8
DEBUG    | dataproperty._extractor:__to_dp_matrix_mt:595 - shutdown ProcessPoolExecutor: workers=8
DEBUG    | dataproperty._extractor:to_column_dp_list:381 - converting to column dataproperty:
DEBUG    | dataproperty._extractor:to_column_dp_list:405 -   params:
DEBUG    | dataproperty._extractor:to_column_dp_list:405 -     prev_col_count=None
DEBUG    | dataproperty._extractor:to_column_dp_list:405 -     matrix_formatting=MatrixFormatting.TRIM
DEBUG    | dataproperty._extractor:to_column_dp_list:405 -     column_type_hints=()
DEBUG    | dataproperty._extractor:to_column_dp_list:407 -   results:
DEBUG    | dataproperty._extractor:to_column_dp_list:436 -     column=0, type=STRING, align=left, ascii_width=6
DEBUG    | dataproperty._extractor:to_column_dp_list:436 -     column=1, type=STRING, align=left, ascii_width=7
DEBUG    | dataproperty._extractor:to_column_dp_list:436 -     column=2, type=STRING, align=left, ascii_width=6
DEBUG    | simplesqlite.core:create_table:1261 - CREATE TABLE IF NOT EXISTS 'class' (device TEXT, classid TEXT, rate TEXT)
DEBUG    | simplesqlite.core:insert_many:617 - insert 2 records into class
DEBUG    | simplesqlite.core:commit:1559 - commit: path=':memory:'
DEBUG    | tcconfig.parser._class:parse:54 - tc class parse result: [
    {
        "device": "mgmt0",
        "classid": "1f36:1",
        "rate": "10Gbps"
    },
    {
        "device": "mgmt0",
        "classid": "1f36:2",
        "rate": "2Mbps"
    }
]
DEBUG    | subprocrunner._subprocess_runner:__debug_print_command:264 - /usr/sbin/tc filter show dev mgmt0
DEBUG    | tcconfig.parser._filter:parse:93 - failed to parse mangle: filter parent 1f36: protocol ip pref 5 u32 chain 0
DEBUG    | tcconfig.parser._filter:parse:127 - failed to parse flow id: filter parent 1f36: protocol ip pref 5 u32 chain 0
DEBUG    | tcconfig.parser._filter:parse:137 - failed to parse filter: filter parent 1f36: protocol ip pref 5 u32 chain 0
DEBUG    | tcconfig.parser._filter:parse:93 - failed to parse mangle: filter parent 1f36: protocol ip pref 5 u32 chain 0 fh 800: ht divisor 1
DEBUG    | tcconfig.parser._filter:parse:127 - failed to parse flow id: filter parent 1f36: protocol ip pref 5 u32 chain 0 fh 800: ht divisor 1
DEBUG    | tcconfig.parser._filter:parse:137 - failed to parse filter: filter parent 1f36: protocol ip pref 5 u32 chain 0 fh 800: ht divisor 1
DEBUG    | tcconfig.parser._filter:parse:93 - failed to parse mangle: filter parent 1f36: protocol ip pref 5 u32 chain 0 fh 800::800 order 2048 key ht 800 bkt 0 flowid 1f36:2 not_in_hw
DEBUG    | tcconfig.parser._filter:__parse_flow_id:184 - succeed to parse flow id: flow-id=1f36:2, line=filter parent 1f36: protocol ip pref 5 u32 chain 0 fh 800::800 order 2048 key ht 800 bkt 0 flowid 1f36:2 not_in_hw
DEBUG    | tcconfig.parser._filter:__parse_protocol:190 - succeed to parse protocol: protocol=ip, line=filter parent 1f36: protocol ip pref 5 u32 chain 0 fh 800::800 order 2048 key ht 800 bkt 0 flowid 1f36:2 not_in_hw
DEBUG    | tcconfig.parser._filter:__parse_priority:197 - succeed to parse priority: priority=5, line=filter parent 1f36: protocol ip pref 5 u32 chain 0 fh 800::800 order 2048 key ht 800 bkt 0 flowid 1f36:2 not_in_hw
DEBUG    | tcconfig.parser._filter:__parse_filter_id:204 - succeed to parse filter id: filter-id=800::800, line=filter parent 1f36: protocol ip pref 5 u32 chain 0 fh 800::800 order 2048 key ht 800 bkt 0 flowid 1f36:2 not_in_hw
DEBUG    | tcconfig.parser._filter:parse:93 - failed to parse mangle: match c0a80763/ffffffff at 16
DEBUG    | tcconfig.parser._filter:parse:127 - failed to parse flow id: match c0a80763/ffffffff at 16
DEBUG    | tcconfig.parser._filter:__parse_filter_ipv4:363 - succeed to parse ipv4 filter: src_network=None, dst_network=192.168.7.99/32, src_port=None, dst_port=None, line=match c0a80763/ffffffff at 16
DEBUG    | tcconfig.parser._filter:parse:93 - failed to parse mangle: match 00000000/00000000 at 12
DEBUG    | tcconfig.parser._filter:parse:127 - failed to parse flow id: match 00000000/00000000 at 12
DEBUG    | tcconfig.parser._filter:__parse_filter_ipv4:363 - succeed to parse ipv4 filter: src_network=0.0.0.0/0, dst_network=192.168.7.99/32, src_port=None, dst_port=None, line=match 00000000/00000000 at 12
DEBUG    | simplesqlite.core:insert_many:617 - insert 1 records into filter
DEBUG    | subprocrunner._subprocess_runner:__debug_print_command:264 - /usr/sbin/tc qdisc show dev mgmt0
DEBUG    | tcconfig.parser._qdisc:parse:65 - parse a qdisc entry: {'direct_qlen': 1000, 'parent': '1f36:2', 'device': 'mgmt0', 'handle': '246c:'}
DEBUG    | simplesqlite.core:insert_many:617 - insert 1 records into qdisc
DEBUG    | simplesqlite.core:close:1583 - close connection to a SQLite database: path=':memory:'
DEBUG    | simplesqlite.core:commit:1559 - commit: path=':memory:'
DEBUG    | simplesqlite.core:connect:265 - connect to a SQLite database: path=':memory:', mode=w
DEBUG    | simplesqlite.core:close:1583 - close connection to a SQLite database: path=':memory:'
DEBUG    | simplesqlite.core:commit:1559 - commit: path=':memory:'
DEBUG    | simplesqlite.core:create_table:1261 - CREATE TABLE IF NOT EXISTS 'filter' (device TEXT NOT NULL, "filter_id" TEXT, flowid TEXT, protocol TEXT, priority INTEGER, [src-network] TEXT, [dst-network] TEXT, [src-port] INTEGER, [dst-port] INTEGER, classid TEXT, handle INTEGER)
DEBUG    | simplesqlite.core:close:1583 - close connection to a SQLite database: path=':memory:'
DEBUG    | simplesqlite.core:commit:1559 - commit: path=':memory:'
DEBUG    | simplesqlite.core:create_table:1261 - CREATE TABLE IF NOT EXISTS 'qdisc' (device TEXT NOT NULL, "direct_qlen" INTEGER, parent TEXT NOT NULL, handle TEXT NOT NULL, delay TEXT, [delay-distro] TEXT, loss TEXT, duplicate TEXT, corrupt TEXT, reorder TEXT, rate TEXT)
DEBUG    | subprocrunner._subprocess_runner:__debug_print_command:264 - /usr/sbin/tc filter show dev mgmt0 root
DEBUG    | tcconfig._common:logging_context:28 - |---- start: _make_qdisc -----
DEBUG    | subprocrunner._subprocess_runner:__debug_print_command:264 - /usr/sbin/tc qdisc add dev mgmt0 root handle 1f36: htb default 1
ERROR    | tcconfig._common:run_command_helper:144 - command execution failed
  command=/usr/sbin/tc qdisc add dev mgmt0 root handle 1f36: htb default 1
  stderr=Error: Exclusivity flag on, cannot modify.

DEBUG    | subprocrunner._subprocess_runner:__debug_print_command:264 - /usr/sbin/tc class add dev mgmt0 parent 1f36: classid 1f36:1 htb rate 10000000.0kbit
DEBUG    | tcconfig._common:logging_context:32 - ----- complete: _make_qdisc ----|
DEBUG    | tcconfig._common:logging_context:28 - |---- start: _add_rate -----
DEBUG    | subprocrunner._subprocess_runner:__debug_print_command:264 - /usr/sbin/tc class show dev mgmt0
DEBUG    | tcconfig.shaper.htb:__get_unique_qdisc_minor_id:253 - existing class list with dev mgmt0: ['class htb 1f36:1', 'class htb 1f36:2']
DEBUG    | tcconfig.shaper.htb:__get_unique_qdisc_minor_id:255 - existing minor classid list with dev mgmt0: [1, 2]
DEBUG    | tcconfig.shaper.htb:_get_qdisc_minor_id:43 - __get_unique_qdisc_minor_id: 3
DEBUG    | subprocrunner._subprocess_runner:__debug_print_command:264 - /usr/sbin/tc class add dev mgmt0 parent 1f36: classid 1f36:3 htb rate 4000.0Kbit ceil 4000.0Kbit burst 500.0KB cburst 500.0KB
DEBUG    | tcconfig._common:logging_context:32 - ----- complete: _add_rate ----|
DEBUG    | tcconfig._common:logging_context:28 - |---- start: _set_netem -----
DEBUG    | subprocrunner._subprocess_runner:__debug_print_command:264 - /usr/sbin/tc qdisc show dev mgmt0
DEBUG    | tcconfig.shaper.htb:__extract_exist_netem_major_ids:274 - existing netem list with dev mgmt0: ['qdisc htb 1f36', 'qdisc netem 246c']
DEBUG    | tcconfig.shaper.htb:__get_unique_netem_major_id:286 - existing netem major id list with dev mgmt0: [7990, 9324]
DEBUG    | subprocrunner._subprocess_runner:__debug_print_command:264 - /usr/sbin/tc qdisc add dev mgmt0 parent 1f36:3 handle 2289: netem
DEBUG    | tcconfig._common:logging_context:32 - ----- complete: _set_netem ----|
DEBUG    | tcconfig._common:logging_context:28 - |---- start: _add_exclude_filter -----
DEBUG    | tcconfig.shaper.htb:_add_exclude_filter:154 - no exclude filter found
DEBUG    | tcconfig._common:logging_context:32 - ----- complete: _add_exclude_filter ----|
DEBUG    | tcconfig._common:logging_context:28 - |---- start: _add_filter -----
DEBUG    | subprocrunner._subprocess_runner:__debug_print_command:264 - /usr/sbin/tc filter add dev mgmt0 protocol ip parent 1f36: prio 5 u32 match ip dst 192.168.7.98/32 match ip src 0.0.0.0/0 flowid 1f36:3
DEBUG    | tcconfig._common:logging_context:32 - ----- complete: _add_filter ----|
DEBUG    | simplesqlite.core:close:1583 - close connection to a SQLite database: path=':memory:'
DEBUG    | simplesqlite.core:commit:1559 - commit: path=':memory:'
DEBUG    | tcconfig._main:_dump_history:75 - command history
/usr/sbin/tc qdisc add dev mgmt0 root handle 1f36: htb default 1
/usr/sbin/tc class add dev mgmt0 parent 1f36: classid 1f36:1 htb rate 10000000.0kbit
/usr/sbin/tc class add dev mgmt0 parent 1f36: classid 1f36:3 htb rate 4000.0Kbit ceil 4000.0Kbit burst 500.0KB cburst 500.0KB
/usr/sbin/tc qdisc add dev mgmt0 parent 1f36:3 handle 2289: netem
/usr/sbin/tc filter add dev mgmt0 protocol ip parent 1f36: prio 5 u32 match ip dst 192.168.7.98/32 match ip src 0.0.0.0/0 flowid 1f36:3
open@redskull:~$ `

**Comment by StormYudi** [comment]
Same here
After:
root@Router:~# tcset eth1 --network 172.16.1.3/32 --rate 0.25Mbps --add
root@Router:~# tcset eth1 --network 172.16.1.4/32 --rate 0.25Mbps --add
[ERROR] command execution failed
  command=/sbin/tc qdisc add dev eth1 root handle 16f1: htb default 1
  stderr=Error: Exclusivity flag on, cannot modify.

**Comment by nobitran** [comment]
Same with me. 
<img width="813" alt="image" src="https://user-images.githubusercontent.com/106733555/197743264-85408978-1221-4ae1-92f1-5650c4970740.png">

Step: 
- sudo tcset tun0 --direction incoming --rate 10Mbps --src-network 10.8.0.6/32
- I want to change the rate from 10 -> 15Mbps 
sudo tcset tun0 --direction incoming --rate 15Mbps --src-network 10.8.0.6/32 --change
but it got error (image above)
[INFO] clipping specified bandwidth rate limit with the tun0 maximum bandwidth rate
(15.0Mbps -> 10.0Mbps)

[ERROR] command execution failed
  command=/sbin/tc qdisc add dev tun0 ingress
  stderr=Error: Exclusivity flag on, cannot modify.

[ERROR] command execution failed
  command=/sbin/tc qdisc change dev ifb7038 parent 1b7e:2 handle 243f: netem
  stderr=Error: NLM_F_REPLACE needed to override.


Additional: With outgoing, the flag --change run success, I can change the rate, but incoming are not
