### ISSUE TITLE
Nested shapping

### ISSUE THREAD

**Issue by draskolnikova** [thombashi/tcconfig#135]
Hello!

I am trying to create nested shapping using this kind of shapping tree.

```
- parent - 1G (all prefix are inserted here)
   - child a - 500m - more specific prefix /29
   - child b - 500m - another specific prefix /29
      - specific host - 10m - /32 ip address
```

Is it possible to do that using tc?

**Comment by thombashi** [comment]
Hello,

`tc` may not has tree setting as it is you are expected, but has filter functionality that might meet your requirements.

Example settings with `tcconfig` commands are as follows:

```
tcset $DEV --delay 10ms --dst-network N.N.N.N/32 --overwrite
tcset $DEV --delay 500ms --dst-network N.N.N.N/29 --add
tcset $DEV --delay 500ms --dst-network N.N.N.N/29 --add
tcset $DEV --rate 1Gbps --add
```
