### ISSUE TITLE
How to implement Jitter?

### ISSUE THREAD

**Issue by severindellsperger** [thombashi/tcconfig#137]
Hi @thombashi

For an application, I need to implement a jitter. In the case that the mean delay is enough large we can work with the `delay-distro` command. For example:
`tcset eth0 --overwrite --delay 10ms --delay-distro 2ms `
The result comes quite close to the selected delay-distro value which in this case represents the jitter value.
We face a problem if the mean delay is smaller than the jitter-value. In an example like the following the `delay-distro` approach isn't working successfully:
`tcset eth0 --overwrite --delay 1ms --delay-distro 5ms`
I understand that the problem is originated because the delay value can't be negative and therefore the `delay-distro` action can't take place correctly (+/- delay-distro value can't be applied).

Do you have an idea of how to solve the problem?
Especially the problem if the mean_delay is greater than the jitter value is a tough one...

Kind
severindellsperger

**Comment by severindellsperger** [comment]
I think the problem could be solved if the distribution can be set and isn't set to normally distributed by default

**Comment by thombashi** [comment]
Hi @severindellsperger,

As you pointed out, the current implementation of `tcconfig` only supports latency that normally distributed.
I will consider adding an option to set delay distribution other than `normal` for future release.

**Comment by thombashi** [comment]
You can now use `--delay-distribution` option with `tcconfig 0.26.0`.
Using `--delay-distribution`, You can use distributions {normal,pareto,paretonormal}.
However, uniform distribution can not be used, caused by `tc`. `tc` command does not accept uniform distribution even though  `tc-netem` man describe that distribution.

https://man7.org/linux/man-pages/man8/tc-netem.8.html

**Comment by severindellsperger** [comment]
Awesome! Thanks for your work. I took a look at the implementation of tc and the source code of the Linux kernel. It looks like the network latency is normally distributed per default. However, the normal distribution would be possible if there exists some normally distributed correlation data on the localhost ([see here for more information](http://www.unixunique.com/2018/07/linux-network-emulator-custom-delay_9.html)).  I wrote my own implementation, which had worked with the normal distribution, and just raised an exception if the needed correlation table was missing. Maybe you can add this feature in a future release (if someone needs it).
