### ISSUE TITLE
tcconfig from python

### ISSUE THREAD

**Issue by V4Vendetta97** [thombashi/tcconfig#140]
hey! is there any documentation now about using tcset directly from python code?

**Comment by V4Vendetta97** [comment]
i find it difficult to understand the source code

**Comment by thombashi** [comment]
Unfortunately, there is no documentation for that usage

**Comment by V4Vendetta97** [comment]
> Unfortunately, there is no documentation for that usage

I need just one simple example please, how can i transform this line to python code please.

tcset enp0s3 --dst-network 192.168.0.0  --rate 2400kbps

**Comment by thombashi** [comment]
How about executing the command from your python code by subprocess call
That would be much more easier.

**Comment by V4Vendetta97** [comment]
Thank your for your reply..
I am already using it as  subprocess calls and it works very well. But for some reasons, i must use it from my python code and i must not use subprocess call. 
I really hope you can help me.

**Comment by thombashi** [comment]
>But for some reasons, i must use it from my python code and i must not use subprocess call.

Why and for what reasons?

`tcconfig` does not support as library usage for now and not recommended for such use cases. The internal interface will change from time to time and that will corrupt backward compatibility of your code.
