### ISSUE TITLE
tcdel --tc-command returns non-zero on exit

### ISSUE THREAD

**Issue by Mnkras** [thombashi/tcconfig#142]
It looks like `tcdel --tc-command` returns a non-zero exit status even though it was successful.
While using `--tc-command` it shouldn't ever return something besides 0.

This makes automating around it very painful

```
$ tcdel --tc-command veth1
/sbin/tc qdisc del dev veth1 root
/sbin/tc qdisc del dev veth1 ingress
/sbin/tc qdisc del dev ifb7272 root
/bin/ip link set dev ifb7272 down
/bin/ip link delete ifb7272 type ifb
$ echo $?
1
```

**Comment by thombashi** [comment]
@Mnkras 
Thank you for your report.

The problem has fixed at `tcconfig 0.25.3`.
Please upgrade the package.
