### ISSUE TITLE
Unable to use tcset --import-setting with --tc-command or --tc-script

### ISSUE THREAD

**Issue by Mnkras** [thombashi/tcconfig#143]
When using `--import-setting` with `--tc-command` or `--tc-script`, they seem to be ignored.

I would expect the commands that are going to be run be output, in reality, it does nothing.

Looks like it goes into dry-run mode and doesn't print anything or perform any commands at all.

**Comment by thombashi** [comment]
Thank you for your report.

That usage is not currently supported. I did not expect that usage when I create it.
I will consider the feature for the future release.

**Comment by thombashi** [comment]
I had released `tcconfig 0.26.0` which includes the feature.
