### ISSUE TITLE
Slow Execution in TcShapingRuleFinder.is_exist_rule

### ISSUE THREAD

**Issue by tkoch96** [thombashi/tcconfig#148]
I thought it might be useful to bring a performance problem to someone's attention, in case they could explain whether or not the below behavior is necessary, or if it can be avoided with ease (I don't have a great understanding of the codebase).

Profiling basic usage of tcset (e.g. tcset --device [device_name]  --add rate 1Mbps) shows that a very large fraction of time is spent in TcShapingRuleFinder.is_exist_rule (which is called in tcset.run). This long run-time is due principally to a line in _filter.parse:

`Filter.insert(
                    Filter(
                        **{
                            Tc.Param.DEVICE: self.__device,
                            Tc.Param.CLASS_ID: self.__classid,
                            Tc.Param.HANDLE: self.__handle,
                        }
                    )
                )`

Insert is a function built into simplesqlite. The long wait here is caused by several calls to deepcopy which is notoriously slow.

Commenting out tcset.py:248-264 results in a ~40x speedup of the basic example above. I'm not suggesting commenting it out is a great solution (I'm sure this line is important), but perhaps it's worth optimizing this call a little?

**Comment by thombashi** [comment]
I don't think this is a performance issue. Because `tcset` command execution completed about 0.5 secs in my environments, this is acceptable to me. However, if you or certain number of people think this is a performance issue, I will consider optimization.

So, those who think `tcset` has a performance issue, please describe info, such as your situations, expectations, actual results, environments, etc.

**Comment by tkoch96** [comment]
I'm personally interested in using tcconfig on lots (say 20) of virtual networks to constrain their available bandwidth. I'd like to do update the constraints every ~3-5 seconds. At the current rate of execution this doesn't seem possible.

I'd be willing to work on this myself if you believe its possible to significantly lower the execution time of tcset.

**Comment by thombashi** [comment]
I believe you can optimize execution time to some extent.
I could not guarantee that satisfy your run time requirements will be met.

PR would be always welcome.
