### ISSUE TITLE
tcdel ignore incoming rules

### ISSUE THREAD

**Issue by drzraf** [thombashi/tcconfig#151]
# Describe the bug
`tcdel eth0 --all` (or `tcdel eth0 --direction incoming`) does not remove incoming rules.
(`ifb*` interfaces still showing in `ip link show`)

# Expected behavior
incoming rules must be removed.

# To Reproduce

1. `tcset --debug --debug-query enp3s0f1 --direction incoming --rate 700kbps --network 1.1.1.1/26`
2. `tcdel enp3s0f1 --all --direction incoming`
3. `ip link show`

# Environments
Please complete the following information:

- **Operating System**: Ubuntu
- **Python Version**: Python 3.8.2
- **tcconfig Version**: 0.26.0
- **Installation Method**: `pip`

**Comment by thombashi** [comment]
Thank you for your report.

I could not reproduce the issue. Looks like a `ifb` device deleted properly in my environment:

```
$ tcdel enp0s3 --all --direction incoming
[INFO] no qdisc to delete for the outgoing device.
[INFO] delete enp0s3 qdisc
[INFO] no qdisc to delete for the incoming device.
[INFO] delete enp0s3 ingress qdisc
```

- Operating System: Ubuntu 18.04
- Python Version: Python 3.8.5
- tcconfig Version: 0.26.0
- Installation Method: pip

Please describe the exact Ubuntu version and the full output of `tcdel` command (with `--debug` option would be preferable).
