### ISSUE TITLE
Unit tests require full installation

### ISSUE THREAD

**Issue by fredleb** [thombashi/tcconfig#154]
I'm new to unit test in Python, so I guess I am doing something wrong here.

I want to add a couple of features to your very useful project, but before I do, I want to make sure the unit tests work.
I had no idea how to run them properly (inside a docker container for many reasons) but after a while I got some results.

First I create a fake device in the container:
`sudo ip link add name radio0 link eth0 address 00:01:02:aa:bb:11 type macvtap`

Then I run (from the root directory):
`PATH=/sbin:$PATH pytest --md-report --device=radio0`

(PATH fix being because my PATH is not what your tests expect - this does not matter)

However most of the tests fail because they try to call the "tcdel", "tcshow", etc... commands directly as if they were installed on the system (but they are not)...

The only way I found to go a bit further is to build the deb package and install it. But this takes forever.
I would like to test the python scripts directly.

I am doing everything wrong here ?
How am I supposed to run the unit tests ?

Thanks ! Great project !

**Comment by thombashi** [comment]
@fredleb 
Please try the followings:

1. `cd <path to the cloned tcconfig dir>`
2. `make setup`

The above commands will install test dependencies.
