### ISSUE TITLE
How to implement different network routes to different interfaces

### ISSUE THREAD

**Issue by jintli** [thombashi/tcconfig#159]
# Is your feature request related to a problem? Please describe.
I have two ISP network connected to two interfaces and how can I implement that different source network route to specify interface?

# Describe the solution you'd like
I think I can use --exclude-src-network? But I don't want to limit any rate or delay or other options.

# Describe alternatives you've considered
None

# Additional context
None

thx!!!

**Comment by thombashi** [comment]
I'm not sure what did you trying to achieve and what the problem is.
Could you possibly describe more detailed information?
Use cases, what is your problems, relation with `tcconfig`, etc.
