### ISSUE TITLE
Distinguish upload and download

### ISSUE THREAD

**Issue by FelixChan0829** [thombashi/tcconfig#162]
# Describe the solution you'd like
Hi, if there any way to distinguish upload and download? Especially for latency and packet loss. I found another tc-based [tool](https://github.com/magnific0/wondershaper) that can distinguish between uploads and downloads, but it can only limit the bandwidth. And I don't understand the principle of its code...

# Additional context
I actually found that both [Windows](https://github.com/skywind3000/clumsy) and [macOS](https://nshipster.com/network-link-conditioner/) have weak network emulation tools that can differentiate between uplink and downlink, and they both work on bandwidth, latency and packet loss. But it seems that Linux doesn't have such a tool yet

**Comment by FelixChan0829** [comment]
Okay, I found a [tutorial](https://wiki.linuxfoundation.org/networking/netem#how_can_i_use_netem_on_incoming_traffic3f) that teaches me how to shape the downlink.

**Comment by thombashi** [comment]
You can use `--direction` option

```
  --direction {outgoing,incoming}
                        the direction of network communication that imposes traffic control. 'incoming' requires ifb kernel module and Linux kernel 2.6.20 or later. (default = outgoing)
```

**Comment by FelixChan0829** [comment]
Oh I see! I miss that option. Thanks!
