### ISSUE TITLE
Add support for setting "limit" parameter

### ISSUE THREAD

**Issue by ReubenM** [thombashi/tcconfig#170]
From what I understand, with netem the "limit" parameter controls the packet queue size. When adding artificial latency, these packets accumulate in the queue, and with high traffic at high latency can start to overflow.

The default is 1000. It would be nice to be able to optionally set that to a much larger value.

**Comment by Scorpionchiques** [comment]
I made this

https://github.com/thombashi/tcconfig/pull/185

**Comment by thombashi** [comment]
Resolved by #185
