### ISSUE TITLE
Dummy .deb package inside tcconfig_0.28.0_jammy_amd64.deb

### ISSUE THREAD

**Issue by Lastique** [thombashi/tcconfig#179]
# Describe the bug

There is `tcconfig_0.28.0_amd64.deb` file in the root filesystem in the `tcconfig_0.28.0_jammy_amd64.deb` package. The `tcconfig_0.28.0_amd64.deb` file seems to be a broken .deb package too, as `dpkg` is unable to unpack it:

```
$ dpkg -x tcconfig_0.28.0_amd64.deb  .
dpkg-deb: error: unexpected end of file in archive member header in tcconfig_0.28.0_amd64.deb
```

# Expected behavior

There should be no nested packages in the .deb packages.

# To Reproduce

1. Download `tcconfig_0.28.0_jammy_amd64.deb`.
2. Run `dpkg -x tcconfig_0.28.0_jammy_amd64.deb .`.
3. See the extracted contents.

# Environments

- Kubuntu 22.04
- **Installation Method**: `deb package`

**Comment by thombashi** [comment]
Thank you for your report.
The problem has been fixed at `tcconfig v0.28.1`.
