### ISSUE TITLE
tcset not controlling traffic for bridge interfaces

### ISSUE THREAD

**Issue by k3rn3Lp4n1cK** [thombashi/tcconfig#188]
# Describe the bug
Ubuntu 22.04
6 NICs (eno1, eno2, eno3, eno4, eno5, eno6)
bridge configuration
```
bridge name	bridge id		STP enabled	interfaces
br1		8000.3ccccccccccc	no		eno1
							eno2
br2		8000.4ccccccccccc	no		eno3
							eno4
br3		8000.5ccccccccccc	no		eno5
							eno6
```

# Expected behavior
when applying a tcset to a bridge interface, there are no errors.  It does not control the traffic
For example the following command does nothing to br1
`tcset br1 --loss 100%`

# Additional context
Not using docker
Version: 0.29.1
Installed with pip

**Comment by thombashi** [comment]
Thank you for your report.
I just want to confirm one thing: does `tc` work properly with the bridge interfaces?

**Comment by k3rn3Lp4n1cK** [comment]
I found a solution, you can close this issue. Thanks for responding so quickly!
