### ISSUE TITLE
Multiple rules per interface

### ISSUE THREAD

**Issue by konetzed** [thombashi/tcconfig#43]
I would like to do something like this

tcset --device bond0.310 --rate 500M --network 192.168.2.0/24
tcset --device bond0.310 --rate 100M --network 192.168.0.0/24

The first one succeeds w/o issue but the second command fails.  Is this not something tcconfig can do?

```
root@ubuntu:~# tcset --device bond0.310 --rate 500M --network 192.168.2.0/24
root@ubuntu:~# tcset --device bond0.310 --rate 100M --network 192.168.0.0/24
[2017-01-12 20:53:30.357743] NOTICE: subprocrunner: failed to add qdisc: prio qdisc already exists. execute with --overwrite option if you want to overwrite the existing settings.
[2017-01-12 20:53:30.367540] NOTICE: subprocrunner: failed to add qdisc: netem qdisc already exists. execute with --overwrite option if you want to overwrite the existing settings.
[2017-01-12 20:53:30.377499] WARNING: subprocrunner: returncode=2, stderr=RTNETLINK answers: File exists
root@ubuntu:~#
```

**Comment by konetzed** [comment]
Also using tcconfig (0.7.0a2) installed via pip on ubuntu 16.04

**Comment by thombashi** [comment]
@konetzed
`tcconfig` has no capability to do that until `0.7.0-alpha2`.
So, I've added the feature with `0.7.0-alpha3`.
In this version, you can add multiple rules to a same interface with `--add` option like the below.

```
tcset --device bond0.310 --rate 500M --network 192.168.2.0/24
tcset --device bond0.310 --rate 100M --network 192.168.0.0/24 --add
```

Could you try this version?
Does it fulfill your requirements?

**Comment by thombashi** [comment]
I'll close the issue since the future added to the `tcconfig 0.7.0`.
Any feedback would be welcome.
Feel free to reopen.

Thanks,

**Comment by konetzed** [comment]
Wanted to say thanks for this, I didn't see the update on the issue until now!

**Comment by thombashi** [comment]
You are welcome.
