### ISSUE TITLE
iptables rules for src network?

### ISSUE THREAD

**Issue by konetzed** [thombashi/tcconfig#49]
Is there a reason why you use iptables for src network when filter rules could do it instead?  

Example

tc qdisc add dev bond0.310 root handle 1: prio bands 10
tc qdisc add dev bond0.310 parent 1:1 handle 10: netem delay 0ms
tc qdisc add dev bond0.310 parent 10:1 handle 11: netem loss 0%
tc qdisc add dev bond0.310 parent 11:1 handle 12: htb default 1
tc class add dev bond0.310 parent 12: classid 0:1 htb rate 200mbit ceil 200mbit
tc filter add dev bond0.310 protocol ip parent 1:0 prio 1 u32 match ip src 192.168.2.0/24 match ip dst 192.168.1.0/24 flowid 10:1

**Comment by thombashi** [comment]
The reason to use iptables is that setting for both `src` and `dst` by `tc filter` is not properly worked 
(at least in my environment).

**Comment by konetzed** [comment]
Thanks for the reply.  I am testing on ubuntu 16.04, 4.4.0-47-generi x86_64 and the src dst are working fine.  My issue is I am building out a wan simulator for multiple networks with many rules based off settings for each wan link.  I am thinking switching from tc rules to iptables rules could add in extra latency and overhead using different parts of the kernel stack, netfliter and netem vs just netem. 

Just wondering what distro kernel is your test env?

**Comment by thombashi** [comment]
Thank you for explaining the background.

My testing environments are Fedora 24 and Debian 8.6 (mainly Fedora).

**Comment by thombashi** [comment]
I'll close the issue.
Since About a month elapsed from the last answer.
Feel free to reopen.
