### ISSUE TITLE
Clear rules from interface 

### ISSUE THREAD

**Issue by konetzed** [thombashi/tcconfig#50]
I am wondering if there is any way to remove rules from an interface using tcset?  I cannot seem to find anything in the docs.  http://tcconfig.readthedocs.io/en/latest/pages/usage/tcset/index.html

Not looking to remove a matching rule but looking to clear all rules like a tcset --clear.  Hopefully that makes sense.  "Basically tc qdisc del dev <device> root"

**Comment by thombashi** [comment]
@konetzed 
You can clear rules from an interface by using `tcdel --device <interface>`.
http://tcconfig.readthedocs.io/en/latest/pages/usage/tcdel/index.html
Is this what you expected?

**Comment by konetzed** [comment]
Yes, sorry did not see this in the docs.

**Comment by thombashi** [comment]
I've added some description of `tcdel` command in `tcset` document.
(http://tcconfig.readthedocs.io/en/latest/pages/usage/tcset/index.html)
Thank you for your feedback.

I'll close the issue.
