### ISSUE TITLE
Add SrcPort matching

### ISSUE THREAD

**Issue by lauhen** [thombashi/tcconfig#51]
Hi,
currently you only support matching on the destination port with `--port`.
How about adding a source port match as well?
Thank you.

**Comment by thombashi** [comment]
@lauhen 
Thank you for your suggestion. Please let me clarify that your question.
What is your intention that "source port match" in this case? I come up with two cases:

1. all of the traffic from certain port
2. specific traffic route (e.g. traffic shaping to packets that routing from port 1234  to port 5678)
    - like `--network` and `--src-network` options of `tcset`

Did you mention 1. or 2. (or both 1. and 2.)?

**Comment by lauhen** [comment]
Thanks for your reply and sorry for the late answer:

1. I want to match all the packets coming from a certain port, the destination port in this case is not important. I tried it with `tcset --device eth0 --direction incoming --port 80 --delay 100` but the `--debug` message tells me that it's still matching on `dport` not on `sport`
A suggestion would be to split the `--port` argument into `--sport` and `--dport` so you could match on either the source-port or the destination-port or even both.

Thank you

**Comment by thombashi** [comment]
Thank you for your answer.

>I want to match all the packets coming from a certain port,

You can achieve that by the `tcset --device eth0 --direction incoming --port 80 --delay 100` command (ingress qdisc behave like sport although the command option is dport)

>the source-port or the destination-port or even both.

However, the last case surely not achievable for the current `tccset`.
I will consider the option in the future release.

**Comment by thombashi** [comment]
@lauhen
I've added source port match feature at `tcconfig 0.10.0` (`--src-port` option).

Thank you for your suggestion.

**Comment by tkoch96** [comment]
Is there any current way to specify one shared rule among several ports? Lets say one IP has open connections on 3 ports, and I want to limit the aggregate available bandwidth to 1Mbps over all these ports. I'm aware I can do 3 separate rules for each port, and limit available  bandwidth to something that sums to 1Mbps, but this is a solution to a slightly different problem.
