### ISSUE TITLE
Set parameter from / to 

### ISSUE THREAD

**Issue by Fraccaman** [thombashi/tcconfig#65]
Would be possible to add, as a parameter, the possibility to specify a rule only from a specific port/ip versus another specific port/ip?
For example, add a 500ms latency only from port 13000 to 14000.

**Comment by thombashi** [comment]
Yes, it is possible to do that by ``--src-port``/``--dst-port`` or ``--src-network``/``--dst-network`` options.
Examples:

## add a 500ms latency only from port 13000 to 14000
```
# tcset --device eth0 --delay 500 --src-port 13000 --dst-port 14000 
# tcshow --device eth0
{
    "eth0": {
        "outgoing": {
            "network=0.0.0.0/0, src-port=13000, dst-port=14000, protocol=ip": {
                "delay": "500.0",
                "rate": "1G"
            }
        },
        "incoming": {}
    }
}
```

## add a 500ms latency only from network 192.168.0.100/32 to 192.168.0.200/32
```
# tcset --device eth0 --delay 500 --src-network 192.168.0.100/32 --dst-network 192.168.200/32 --iptables
# tcshow --device eth0
{
    "eth0": {
        "outgoing": {
            "network=192.168.200/32, src-network=192.168.0.100/32, protocol=all": {
                "delay": "500.0",
                "rate": "1G"
            }
        },
        "incoming": {}
    }
}
```

**Comment by Fraccaman** [comment]
Oh, I think I've missed that in the docs. Thank you!

**Comment by thombashi** [comment]
It was my pleasure.
I'll close the issue then.
Feel free to reopen.
