### ISSUE TITLE
tcshow show incorrect limits when overwriting existing limit with tcset --add

### ISSUE THREAD

**Issue by twdkeule** [thombashi/tcconfig#70]
Commands:
```
➜  ~ sudo tcset --device lo --rate 10M                
➜  ~ sudo tcset --device lo --rate 5M --add 
➜  ~ tcshow --device lo                 
{
    "lo": {
        "outgoing": {
            "network=0.0.0.0/0, protocol=ip": {
                "rate": "5M"
            }
        },
        "incoming": {}
    }
}
```
iperf3 keeps measuring the actual limit as 10 Mbps while tcshow shows 5 Mbps

**Comment by thombashi** [comment]
Thank you for your report.

Certainly, these are not a preferable behavior.
I think that there are two problems:

1. `tcshow` only display the last `tc` setting
2. `tcset` allow multiple shaping rules for the same device and the same network
    - `--add` option should allow only when different rules for the different devices/networks

I will fix `2.` in the future release, and `1.` will never happen if I fix `2.`

**Comment by twdkeule** [comment]
Well 1. can still occur if you make a script with `--tc-script` and apply that, or when you run `tc` by itself.
It would be very nice if `tcshow` would parse the output of `tc qdisc show`, so it would always be correct. However, this might take it too far.

I am also a bit confused what the `--add` option does. What would be the difference between
```
➜  ~ sudo tcset --device lo --rate 10M
➜  ~ sudo tcset --device lo --delay 10
```
and
```
➜  ~ sudo tcset --device lo --rate 10M
➜  ~ sudo tcset --device lo --delay 10 --add
```

**Comment by thombashi** [comment]
I've fixed the `2.` at `tcconfig 0.12.0`.

>Well 1. can still occur if you make a script with --tc-script and apply that, or when you run tc by itself.
>It would be very nice if tcshow would parse the output of tc qdisc show, so it would always be correct. However, this might take it too far.

You are absolutely right. However, that is out of scope (at least for now).
`tcshow` only aims to show the settings by `tcset` (too many things to consider to create general purpose `tc` setting display tool)

>I am also a bit confused what the --add option does. What would be the difference between

Purpose `--add` option is to set multiple shaping rules to a device as follows:

```
# tcset --device eth0 --network 192.168.0.0/24 --delay 10
# tcset --device eth0 --network 192.168.1.0/24 --delay 50
[NOTICE] tcconfig: failed to 'tc qdisc add': qdisc already exists (dev eth0, handle=1a1a:, algo=htb). execute with --overwrite option if you want to overwrite the existing rules. execute with --add option if you want to add a new rule in addition to the existing rules.
```

```
# tcset --device eth0 --network 192.168.1.0/24 --delay 50 --add
# tcshow --device eth0
{
    "eth0": {
        "outgoing": {
            "dst-network=192.168.1.0/24, protocol=ip": {
                "delay": "50.0",
                "rate": "1G"
            },
            "dst-network=192.168.0.0/24, protocol=ip": {
                "delay": "10.0",
                "rate": "1G"
            }
        },
        "incoming": {}
    }
}
```

**Comment by twdkeule** [comment]
Thanks, now I get it.

**Comment by thombashi** [comment]
I'll close the issue then.
Thanks,
