### ISSUE TITLE
Add support for network exclusion parameter in tcset

### ISSUE THREAD

**Issue by dastergon** [thombashi/tcconfig#77]
Hi,

It would be great to see an exclusion parameter in tcconfig which will exclude the rules to a specific network.  

e.g., Apply the delay to everyone but the 192.16.0.10 network:

     # tcset --device eth0 --delay 100 --exclude-network 192.168.0.10

or to a specific CIDR:

     # tcset --device eth0 --delay 100 --exclude-network 192.168.0.10/24

Example of tc command for network exclusion of packets of 192.168.1.15 with destination port 9001:
```
tc filter add dev eth0 protocol ip parent 1:0 prio 3 u32 match ip src 0/0 flowid 1:3
tc filter add dev eth0 protocol ipv6 parent 1:0 prio 4 u32 match ip6 src ::/0 flowid 1:3

tc filter add dev eth0 protocol ip parent 1:0 prio 1 u32 match ip dport 22 0xffff flowid 1:2
tc filter add dev eth0 protocol ip parent 1:0 prio 1 u32 match ip sport 22 0xffff flowid 1:2
tc filter add dev eth0 protocol ip parent 1:0 prio 1 u32 match ip src 192.168.1.15 match ip dport 9001 0xffff flowid 1:2

tc filter add dev eth0 protocol ipv6 parent 1:0 prio 2 u32 match ip6 dport 22 0xffff flowid 1:2
tc filter add dev eth0 protocol ipv6 parent 1:0 prio 2 u32 match ip6 sport 22 0xffff flowid 1:2
tc filter add dev eth0 protocol ipv6 parent 1:0 prio 2 u32 match ip6 dport 9001 0xffff flowid 1:2
```
    
Thanks,
Pavlos

**Comment by thombashi** [comment]
@dastergon 
Thank you for your suggestion and examples.

An exclusion parameter surely a good feature.
I will consider the feature in the next release.

**Comment by thombashi** [comment]
@dastergon
I've added following exclude options at `tcconfig 0.13.0`:

- `--exclude-dst-network`
- `--exclude-src-network`
- `--exclude-dst-port`
- `--exclude-src-port`

Please check that out.
I would appreciate any feedback or comments.

Thanks,
