### ISSUE TITLE
Issue configuring bandwidth rate on a certain network interface

### ISSUE THREAD

**Issue by dastergon** [thombashi/tcconfig#81]
I would like to change the bandwidth rate in a certain network interface, however I get the same error output in all values that I have tried.

```
tcset --device ens3 --rate 1k
[ERROR] tcconfig: bandwidth_rate must be less than -1000: actual=1.0

tcset --device ens3 --rate 1Gbps
[ERROR] tcconfig: bandwidth_rate must be less than -1000: actual=1000000.0

tcset --device ens3 --rate 10Mbps
[ERROR] tcconfig: bandwidth_rate must be less than -1000: actual=10000.0
```
The output of `/sys/class/net/ens3/speed` is `-1`.

If I apply raw `tc` commands like the following, there are no error messages.

```
tc qdisc add dev ens3 handle 1: root htb default 11
tc class add dev ens3 parent 1: classid 1:1 htb rate 1000Mbps
tc class add dev ens3 parent 1:1 classid 1:11 htb rate 4Mbit
tc qdisc add dev ens3 parent 1:11 handle 10: netem delay 50ms
```

Update:

According to the [ABI doc](https://github.com/torvalds/linux/blob/5518b69b76680a4f2df96b1deca260059db0c2de/Documentation/ABI/testing/sysfs-class-net) of the kernel (re: speed): 
```
What: /sys/class/net/<iface>/speed
Description:
Indicates the interface latest or current speed value. Value is
an integer representing the link speed in Mbits/sec.
 
Note: this attribute is only valid for interfaces that implement
the ethtool get_settings method (mostly Ethernet ).
```
From the Linux kernel [source code](https://github.com/torvalds/linux/blob/5518b69b76680a4f2df96b1deca260059db0c2de/net/core/net-sysfs.c#L206) the `__ethtool_get_link_ksettings` function seems to fail and that's why the -1 is returned. My guess is that the virtio drivers are [causing](https://github.com/torvalds/linux/blob/bc78d646e708dabd1744ca98744dea316f459497/drivers/net/virtio_net.c#L1764l) that confusion. [Paravirtualised](https://serverfault.com/questions/738840/get-link-speed-of-an-virtio-net-network-adapter) network interfaces  have no speed because there is no speed limit. 

So would it make sense to add a handling in the code to default to the iproute2 upper bound when it encounters a -1 speed?

**Comment by thombashi** [comment]
@dastergon 
Thank you for your detailed investigation and the pull request.
That's good to know.
I did not know that the para-virtualized network drivers return `-1` to `/sys/class/net/<iface>/speed`.

`ethtool` seems to accept `SPEED_UNKNOWN` (`-1`):
https://github.com/torvalds/linux/blob/a090bd4ff8387c409732a8e059fbf264ea0bdd56/include/uapi/linux/ethtool.h#L1509

```c
static inline int ethtool_validate_speed(__u32 speed)
{
	return speed <= INT_MAX || speed == SPEED_UNKNOWN;
}
```

https://github.com/torvalds/linux/blob/a090bd4ff8387c409732a8e059fbf264ea0bdd56/include/uapi/linux/ethtool.h#L1652

```
 * struct ethtool_link_settings - link control and status
...
 * is up they represent the negotiated link mode; if the link is down,
 * the speed is 0, %SPEED_UNKNOWN or the highest enabled speed and
 * @duplex is %DUPLEX_UNKNOWN or the best enabled duplex mode.
```

>So would it make sense to add a handling in the code to default to the iproute2 upper bound when it encounters a -1 speed?

That makes sense.

I've made some modification for tests (no logic changes), and add test cases.
And now, published at `tcconfig 0.13.1`.
Thank you for your help.
