### ISSUE TITLE
[Documentation] Show two host examples

### ISSUE THREAD

**Issue by dastergon** [thombashi/tcconfig#83]
At the moment there are examples for applying traffic shaping rules to individual hosts. It would be great to see the documentation include some examples i.e., how to set/enforce bandwidth between two hosts.

**Comment by thombashi** [comment]
Thank you for your suggestion.

Could you tell me a little bit more what you expect for `how to set/enforce bandwidth between two hosts` documentation?
Does it one of the following (1) or (2) or any other?

# (1) Routing
e.g. environment: routing host B which reside between A and C.

```
A <--> B <--> C
```

Examples of set shaping rules to the `B` that only affect packets between `A` to `C` by using `--dst-network`, `--src-network` and so on.

# (2) Hosts in a network
e.g. environment: multiple hosts (A, B, C, D) in the same network.

```
A (192.168.0.100) --+--B (192.168.0.2)
                    |
                    +--C (192.168.0.3)
                    |
                    +--D (192.168.0.4)
```

Set a shaping rule from `A` to specific hosts (`B`/`D`) by `--dst-network` and `--exclude-network`

```
tcset -d eth0 --dst-network 192.168.0.0/28 --exclude-dst-network 192.168.0.3 --delay 100
```

**Comment by dastergon** [comment]
@thombashi both examples look great. Could be added in the Advanced usage section in the documentation.

**Comment by thombashi** [comment]
I have updated the document:
http://tcconfig.readthedocs.io/en/latest/pages/usage/tcset/index.html#advanced-usage

Thanks,
