### ISSUE TITLE
Support extra time units in delay specification 

### ISSUE THREAD

**Issue by dastergon** [thombashi/tcconfig#86]
At the moment when using the `--delay` option in `tcset`, you can only set time to milliseconds. According to the `tc` [man page ](http://lartc.org/manpages/tc.txt), it supports microseconds and seconds too. It would be great to have support for those time units plus minutes which could be easily converted to one of the supported time units. 

Examples:

#### e.g. Set 100ms network latency
`# tcset --device eth0 --delay 100ms`

#### e.g. Set 100s network latency
`# tcset --device eth0 --delay 100s`

#### e.g. Set 1m network latency
`# tcset --device eth0 --delay 1m`

Thanks,
Pavlos

**Comment by thombashi** [comment]
Thank you for your suggestion.

That surely makes more easy to set delay time.
I will consider that feature for the next release.

**Comment by thombashi** [comment]
@dastergon
I've added support for time units at `tcconfig 0.15.0`.
Now, you can use the following time units:

us/usec/usecs/microsecond/microseconds
ms/msec/msecs/millisecond/milliseconds
s/sec/secs/second/seconds
m/min/mins/minute/minutes

**Comment by dastergon** [comment]
@thombashi thanks for the quick update! I tested it and works as expected!

**Comment by thombashi** [comment]
Thank you for testing.
I'll close the issue then.
