### ISSUE TITLE
hfsc support

### ISSUE THREAD

**Issue by NetForces** [thombashi/tcconfig#90]
Hi,

  Any plan of WIP for supporting HFSC ?

  Thanks.

**Comment by thombashi** [comment]
Hi,

I have not currently planned to support HSFC (might be supported in the future).
Did you use tc command in a use case that does not support by HTB?

**Comment by NetForces** [comment]
No, just have some legacy code that generates HFSC rules and in the process of refactoring that part and was looking for easier to use helpers.
