### ISSUE TITLE
How can I setup a default sharing rate?

### ISSUE THREAD

**Issue by hu6360567** [thombashi/tcconfig#92]
I'm trying to limit traffic by destination ports.
However, for other applications, I'd like to put them into a default class, which has a very small rate to them.

I haven't found any arguments to set priority.

Is there any solution for this?

```json
{
    "lo": {
        "incoming": {},
        "outgoing": {
            "dst-network=127.0.0.1/32, dst-port=3000, protocol=ip": {
                "rate": "1000M"
            },
            "dst-network=127.0.0.1/32, dst-port=5000, protocol=ip": {
                "rate": "2000M"
            },
            "protocol=ip": {
                "rate": "10M"
            }
        }
    }
}
```
For example, I wanna make the last rule to be the default rule.
All traffic not going to 127.0.0.1:3000/5000 should apply this rule.

**Comment by thombashi** [comment]
@hu6360567 

You could do that.
Filters will apply by added order.
So, the following commands would satisfy your requirement:

```
tcset -d lo --network 127.0.0.1 --dst-port 3000 --rate 1000M --overwrite
tcset -d lo --network 127.0.0.1 --dst-port 5000 --rate 2000M --add
tcset -d lo --rate 10M --add
```

**Comment by thombashi** [comment]
@hu6360567

I'll close the issue.
Feel free to reopen if you still have any problems.
