### ISSUE TITLE
Does tcconfig has any doc for its code achieve?

### ISSUE THREAD

**Issue by a316105362** [thombashi/tcconfig#95]
Hi,
You job is great,I want to learn how its code achieve limit bandwidth.It is hard to read code,does any doc for it.
thank you.

**Comment by thombashi** [comment]
Hi,
As you may already aware, `tcconfig` depends on the `tc` command to limit network bandwidth (htb algorithm).
So, you would need to check `iproute2` package (which include the `tc` command) and their documentation if you would like to know the core algorithm.

**Comment by thombashi** [comment]
I'll close the issue.
Feel free to reopen if you still have any problems about the issue.
