### ISSUE TITLE
qdisc classful type htb

### ISSUE THREAD

**Issue by a316105362** [thombashi/tcconfig#96]
your tcset command use htb qdisc to limit bandwidth, does it a first in first out algorithm.If not, how should I limit bandwidth like physical device limit? like connect two 100Mb PC with a 10Mb switch.

**Comment by thombashi** [comment]
I'm not exactly sure what you intend to do,
if you would try to simulate the situation that network bandwidth saturation,
it would be good to apply traffic shaping rule to software router (with the `--rate 10Mbps` option).

**Comment by a316105362** [comment]
@thombashi 
For example there are 3 machine, A, B, C.
I want to limiit A's bandwidth and use B dos attack A, in order to A can't recive C's packet when dos attack.
I konw your tcset use tc command's htb algorithm like 'tc qdisc add dev eth1 root handle 16f1: htb default 1'. 
Limiting bandwidth must have drop packet method. I have see htb algorithm in [http://linux-ip.net/articles/Traffic-Control-HOWTO/classful-qdiscs.html#qc-htb](url) , but I don't see how it drop packet.
So I want to konw 'htb' drop pacekt random or it is a 'first in first out(fifo)' queue. 
If 'htb' drop packet random I can't really prevent C's packet when B dos A.
thanks for you reply.

**Comment by thombashi** [comment]
@a316105362 
As far as I know, `htb` algorithm is not exactly FIFO. i.e. `htb` will drop packets if there are not enough empty buckets.
If you would like to know more about the algorithm please refer [HTB home]( http://luxik.cdi.cz/~devik/qos/htb/ ), or posting to the tc mailing list would be recommended.
