### ISSUE TITLE
Docs won't display correctly in PyPI

### ISSUE THREAD

**Issue by drozdziak1** [thombashi/tcconfig#97]
It looks like `tcconfig` might have a typo in its documentation which prevents PyPI from displaying the docs correctly.
https://pypi.python.org/pypi/tcconfig

**Comment by thombashi** [comment]
Thank you for your report.

According to my experience, the problem occurred when uploading the package data to PyPI from Travis CI.
The README properly rendered when I upload the same data manually.
I don't know the reason why it happens.

**Comment by thombashi** [comment]
I had Fix the PyPI page.
