### ISSUE TITLE
Add an extra check for capabilities when executing the commands

### ISSUE THREAD

**Issue by dastergon** [thombashi/tcconfig#98]
Besides the execution of the commands as a root user, you can also employ Linux [capabilities](http://man7.org/linux/man-pages/man7/capabilities.7.html) and apply `CAP_NET_ADMIN` and `CAP_NET_RAW` to  `tc` and `iptables` in order to use them as a regular user.

In your [root check](https://github.com/thombashi/tcconfig/blob/master/tcconfig/_common.py#L48) , you could implement an extra check for those two capabilities and permit the execution or else raise an Exception or print an informative error. Currently, I am unable to use `tcconfig` tools due to that check and I have to modify the code and run it again. 

###  How to use capabilities
Get the capabilities of a command:

     getcap /sbin/tc

Set capabilities to a command: 

    setcap cap_net_raw,cap_net_admin+ep /sbin/tc

**Comment by thombashi** [comment]
@dastergon 
Thank you for your feedback.
I will fix the issue in the future release by considering Linux capabilities at permission-check.

**Comment by thombashi** [comment]
@dastergon 
I could not promise the exact release date, but probably within several weeks.
I had limited time for now, the modification itself would relatively small.

**Comment by thombashi** [comment]
@dastergon 
Sorry to keep you waiting.
I had released `tcconfig 0.18.0` that supported Linux capabilities.

**Comment by dastergon** [comment]
@thombashi  thanks a lot! cheers

**Comment by thombashi** [comment]
I'll close the issue.
Feel free to reopen if you have any problem with capabilities.
