### ISSUE TITLE
--tc-command doesn't work with --direction incoming

### ISSUE THREAD

**Issue by user-name-is-taken** [thombashi/tcconfig#99]
The error given when running these together is "[ERROR] tcconfig: network interface not found: ifb4623". I assume this is because of --tc-command's suppression of the commands to create the ifb interface.

**Comment by thombashi** [comment]
@user-name-is-taken 
Thank you for your report.
I had fixed the problem at `tcconfig 0.19.1`.
Please upgrade the package and re-execute the command

**Comment by user-name-is-taken** [comment]
Tested with " tcset --rate 5Gbps --direction incoming --tc-command eth5" and it worked.
